### ISSUE TITLE
Copyright and license reference

### ISSUE THREAD

**Issue by jmillan** [PeterScott/netstring-c#5]
Hi @PeterScott,

I used your code to buid a module in [this](https://github.com/alfredh/baresip) project.

The code was cosmetically modified to fit with the project style. Here the files:

[netstring.c](https://github.com/alfredh/baresip/blob/master/modules/ctrl_tcp/netstring/netstring.c)
[netstring.h](https://github.com/alfredh/baresip/blob/master/modules/ctrl_tcp/netstring/netstring.h)

We'd like to add the corresponding copyright and license headers to these files. I know the the project is Public Domain. May you please indicate which would be the correct text we should add?

Thanks a lot.

**Comment by PeterScott** [comment]
How about "This file is public domain, adapted from
https://github.com/PeterScott/netstring-c/"?

**Comment by jmillan** [comment]
Sounds perfect.

Thanks a lot and congrats for this piece of software.
